### PR TITLE
initial commit progress bar

### PR DESCRIPTION
**Pull request by danielrileyde**
# Context

This PR aims to tackle [Progress Bar](https://github.com/spiced-academy/honey-web-dev/blob/main/sessions/js-functions-2/challenges-js-functions-2.md).

# Changes

- [ ] created a percentage progress bar that syncs with the scroll of the user for the length of the webpage

### CODE REVIEW

**Comment by AntKarpo** [comment]
Looks good.  But why is it called initial commit?

**Comment by AntKarpo** [comment]
Looks good.  But why is it called initial commit?

**Comment by danielrileyde** [comment]
> Looks good. But why is it called initial commit?

Because it is the initial commit to this feature branch. I always know its the first one if anything is wrong and need to bush a new branch.

**Comment by danielrileyde** [comment]
Also thanks for the PR's

**Pull request merged**
